# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0363cf9a7a5684ae21e4d51c121088fbc3d9474a298d8406487a0a984babccbae9e8da31d90ecfec3f346f4743ade5e90e1a3719593419ab85102dbe886145bc

test:
  secret_key_base: 0e0952520811e62675cd3eb59f806e824fce8c0550478355a32ecf34294713d77f5c819c40b6f49eac162af9fa6ff3ce9988f108b1c56494c488726bd5129f55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: efd755f8bcc13a0e13e45bde77132749d9c5f95e4767c039f19e82ae6b34b6b4f736b5bb923f340bf07e05c9ac4951546cca818bdf861c34f5672a641a01b5f7
