# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be55a0a067d9857750a55d0a9545fc1e5d3672eec324276c1ea3acf0d8d59d1bdca063b80a1789f8b0b2312b1c0d70869c12eca9f304d358f41ab89e6d8b066

test:
  secret_key_base: 9bccce80e242a037524f48e8550e46663ca140f2dea5250302717732f3a3ab9c429928b7ea50b266c2a90fc7994c7113d01457509db7c5b60e1633c2f4ca8a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
