# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c352eda4c6cf2494ccaaee17f365e6b28f16599bed05dc55ab12919973e50ea7be279b954e9d25aa9c76c7871c453b182413fdbb1ab8256ef9c1c4e680620985

test:
  secret_key_base: e78817d8f5f3b05c49b8fa4853d5cc2ac5239bc5d0992035212ff0ce4931eb6abecc7002e7b1507ef9a926581e857ff32151c4acbab21e8efe81f1e7c8570596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 364772177573373130d9e46ace299705aaedd489e092659a2214363fc0db3f01b6a4484712d978878e41341888df26a1024dae7e0dcfb1c4c5e4135fe7d56ef7
